<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdManageAttr', 'doctrine');

/**
 * BaseAdManageAttr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property integer $parent
 * @property boolean $status
 * @property integer $priority
 * @property string $lang
 * @property Doctrine_Collection $AdAttr
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getSlug()     Returns the current record's "slug" value
 * @method integer             getParent()   Returns the current record's "parent" value
 * @method boolean             getStatus()   Returns the current record's "status" value
 * @method integer             getPriority() Returns the current record's "priority" value
 * @method string              getLang()     Returns the current record's "lang" value
 * @method Doctrine_Collection getAdAttr()   Returns the current record's "AdAttr" collection
 * @method AdManageAttr        setName()     Sets the current record's "name" value
 * @method AdManageAttr        setSlug()     Sets the current record's "slug" value
 * @method AdManageAttr        setParent()   Sets the current record's "parent" value
 * @method AdManageAttr        setStatus()   Sets the current record's "status" value
 * @method AdManageAttr        setPriority() Sets the current record's "priority" value
 * @method AdManageAttr        setLang()     Sets the current record's "lang" value
 * @method AdManageAttr        setAdAttr()   Sets the current record's "AdAttr" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdManageAttr extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_manage_attr');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'ten thuoc tinh',
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('parent', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 22,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             'comment' => 'trang thai',
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'sap xep',
             'length' => 4,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdManageAttrProduct as AdAttr', array(
             'local' => 'id',
             'foreign' => 'attr_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}