<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdManageAttrProduct', 'doctrine');

/**
 * BaseAdManageAttrProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $attr_id
 * @property string $attr_type
 * @property string $lang
 * 
 * @method integer             getProductId()  Returns the current record's "product_id" value
 * @method integer             getAttrId()     Returns the current record's "attr_id" value
 * @method string              getAttrType()   Returns the current record's "attr_type" value
 * @method string              getLang()       Returns the current record's "lang" value
 * @method AdManageAttrProduct setProductId()  Sets the current record's "product_id" value
 * @method AdManageAttrProduct setAttrId()     Sets the current record's "attr_id" value
 * @method AdManageAttrProduct setAttrType()   Sets the current record's "attr_type" value
 * @method AdManageAttrProduct setLang()       Sets the current record's "lang" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdManageAttrProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_manage_attr_product');
        $this->hasColumn('product_id', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ten thuoc tinh',
             'length' => 22,
             ));
        $this->hasColumn('attr_id', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 22,
             ));
        $this->hasColumn('attr_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => '1: thuoc tinh, 2: thuoc tinh con',
             'length' => 255,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}