<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdMeta', 'doctrine');

/**
 * BaseAdMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $cat_id
 * @property string $meta_type
 * @property string $cat_slug
 * @property string $product_status
 * @property string $product_rate
 * @property integer $product_price
 * @property clob $meta_data
 * @property VtpProducts $AdMetaProduct
 * @property AdArticle $AdMetaArticle
 * 
 * @method integer     getProductId()      Returns the current record's "product_id" value
 * @method integer     getCatId()          Returns the current record's "cat_id" value
 * @method string      getMetaType()       Returns the current record's "meta_type" value
 * @method string      getCatSlug()        Returns the current record's "cat_slug" value
 * @method string      getProductStatus()  Returns the current record's "product_status" value
 * @method string      getProductRate()    Returns the current record's "product_rate" value
 * @method integer     getProductPrice()   Returns the current record's "product_price" value
 * @method clob        getMetaData()       Returns the current record's "meta_data" value
 * @method VtpProducts getAdMetaProduct()  Returns the current record's "AdMetaProduct" value
 * @method AdArticle   getAdMetaArticle()  Returns the current record's "AdMetaArticle" value
 * @method AdMeta      setProductId()      Sets the current record's "product_id" value
 * @method AdMeta      setCatId()          Sets the current record's "cat_id" value
 * @method AdMeta      setMetaType()       Sets the current record's "meta_type" value
 * @method AdMeta      setCatSlug()        Sets the current record's "cat_slug" value
 * @method AdMeta      setProductStatus()  Sets the current record's "product_status" value
 * @method AdMeta      setProductRate()    Sets the current record's "product_rate" value
 * @method AdMeta      setProductPrice()   Sets the current record's "product_price" value
 * @method AdMeta      setMetaData()       Sets the current record's "meta_data" value
 * @method AdMeta      setAdMetaProduct()  Sets the current record's "AdMetaProduct" value
 * @method AdMeta      setAdMetaArticle()  Sets the current record's "AdMetaArticle" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdMeta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_meta');
        $this->hasColumn('product_id', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ten thuoc tinh',
             'length' => 22,
             ));
        $this->hasColumn('cat_id', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'ten thuoc tinh',
             'length' => 22,
             ));
        $this->hasColumn('meta_type', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tiêu đề bài viết',
             'length' => 512,
             ));
        $this->hasColumn('cat_slug', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tiêu đề bài viết',
             'length' => 512,
             ));
        $this->hasColumn('product_status', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tiêu đề bài viết',
             'length' => 512,
             ));
        $this->hasColumn('product_rate', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tiêu đề bài viết',
             'length' => 512,
             ));
        $this->hasColumn('product_price', 'integer', 22, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'Tiêu đề bài viết',
             'length' => 22,
             ));
        $this->hasColumn('meta_data', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung bài viết trên web',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtpProducts as AdMetaProduct', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasOne('AdArticle as AdMetaArticle', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}