<?php
// auto-generated by sfViewConfigHandler
// date: 2020/08/01 02:05:50
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Vinh Thanh SAT', false, false);

  $response->addStylesheet('jquery-ui.css', '', array ());
  $response->addStylesheet('font-awesome-4.2.0/css/font-awesome.min.css', '', array ());
  $response->addStylesheet('lato/css/lato.min.css', '', array ());
  $response->addStylesheet('swiper.css', '', array ());
  $response->addStylesheet('jquery.mmenu.all.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('a.css', '', array ());
  $response->addStylesheet('grid.css', '', array ());
  $response->addStylesheet('flexslider.css', '', array ());
  $response->addJavascript('jquery-1.10.1.min.js', '', array ());
  $response->addJavascript('jquery.form.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.10.3.custom.min.js', '', array ());
  $response->addJavascript('jquery.mmenu.min.all.js', '', array ());
  $response->addJavascript('script.js', '', array ());
  $response->addJavascript('swiper.js', '', array ());
  $response->addJavascript('jquery.flexslider.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('jquery-ui.css', '', array ());
  $response->addStylesheet('font-awesome-4.2.0/css/font-awesome.min.css', '', array ());
  $response->addStylesheet('lato/css/lato.min.css', '', array ());
  $response->addStylesheet('swiper.css', '', array ());
  $response->addStylesheet('jquery.mmenu.all.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('a.css', '', array ());
  $response->addStylesheet('grid.css', '', array ());
  $response->addStylesheet('flexslider.css', '', array ());
  $response->addJavascript('jquery-1.10.1.min.js', '', array ());
  $response->addJavascript('jquery.form.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.10.3.custom.min.js', '', array ());
  $response->addJavascript('jquery.mmenu.min.all.js', '', array ());
  $response->addJavascript('script.js', '', array ());
  $response->addJavascript('swiper.js', '', array ());
  $response->addJavascript('jquery.flexslider.js', '', array ());
}

