<?php

/**
 * AdAdvertiseImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdAdvertiseImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdAdvertiseImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdAdvertiseImage');
    }

    public static function getImageByAdvertiseId($advertiseId)
    {
        $q = AdAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId);
        return $q;
    }

    public static function getImageByAdvertiseIdOrderByPriority($advertiseId)
    {
        $q = AdAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId)
            ->orderBy('priority asc');
        return $q;
    }

    public static function getCountImage($advertiseId)
    {
        $q = AdAdvertiseImageTable::getInstance()->createQuery()
            ->select('file_path, advertise_id, is_active, created_by, created_at')
            ->where('advertise_id=?', $advertiseId);
        return $q->count();
    }

    public static function deleteImageByAdvertise($advertiseId)
    {
        return AdAdvertiseImageTable::getInstance()->createQuery()
            ->delete()
            ->whereIn('advertise_id', $advertiseId)->execute();
    }

    public static function getImageByLocation($location, $limit =5)
    {
        return AdAdvertiseImageTable::getInstance()->createQuery('a')
            ->leftJoin('a.AdAdvertiseLocation b')
            ->andWhere('b.page=?', $location)
            ->orderBy('a.priority asc')
            ->groupBy('a.id')
            ->limit($limit)
            ->execute();
    }

}