<?php

/**
 * AdManageAttrProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdManageAttrProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdManageAttrProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdManageAttrProduct');
    }

    public static function getListAttrByProduct($productId, $attrType = AdManageAttrProduct::ATTR_TYPE_PARENT)
    {
        $query = AdManageAttrProductTable::getInstance()->createQuery()
            ->andWhere('product_id=?', $productId);
        if ($attrType !== false) {
            $query->andWhere('attr_type=?', $attrType);
        }
        $result = $query->execute();
        if ($result) {
            return $result;
        }
        return false;
    }

    /**
     * lay danh sach thuoc tinh theo san pham hoac cat
     * @param $productId : id san pham hoac category
     * @param int $attrType : 1: thuoc tinh cha, 2 thuoc tinhcon, 3: category
     * @return bool
     */
    public static function getArrAttrByProduct($productId, $attrType = AdManageAttrProduct::ATTR_TYPE_PARENT)
    {
        $attrs = self::getListAttrByProduct($productId, $attrType);
        $arrAttr = false;
        if ($attrs) {
            foreach ($attrs as $attr) {
                $obj = $attr->getObjAttr();
                if ($obj)
                    $arrAttr[$attr->attr_id] = $obj->name;
            }
        }
        return $arrAttr;
    }

    public static function updateAttr($productId, $attrId = [], $attrType = AdManageAttrProduct::ATTR_TYPE_CHILD)
    {
        try {
            // xoa du lieu cu
            AdManageAttrProductTable::getInstance()->createQuery()
                ->delete()
                ->andWhere('product_id=?', $productId)
                ->andWhere('attr_type=?', $attrType)
                ->execute();
            // cap nhap ban ghi moi
            if (!empty($attrId)) {
                foreach ($attrId as $id) {
                    $obj = new AdManageAttrProduct();
                    $obj->setProductId($productId);
                    $obj->setAttrId($id);
                    $obj->setAttrType($attrType);
                    $obj->save();
                }
            }
        } catch (Exception $e) {
        }
    }

    public static function getListAttrByCat($slug)
    {
        $query = AdManageAttrProductTable::getInstance()->createQuery('a')
            ->select('a.attr_id, a.product_id,c.name,c.slug')
            ->leftJoin('a.AdCat b')
            ->leftJoin('a.AdAttr c')
            ->andWhere('b.slug=?', $slug)
            ->andWhere('a.attr_type=?', AdManageAttrProduct::ATTR_TYPE_CAT);
        $result = $query->execute();
        if ($result) {
            return $result;
        }
        return false;
    }
}