<?php

/**
 * AdManageAttrTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdManageAttrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdManageAttrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdManageAttr');
    }

    /**
     * lay danh sach thuoc tinh
     * @param bool $status
     * @return bool
     */
    public static function getAllAttr($status = false, $parent = false)
    {
        $query = AdManageAttrTable::getInstance()->createQuery();
        if ($status !== false) {
            $query->andWhere('status=?', $status);
        }
        if ($parent !== false) {
            if (is_array($parent)) {
                $query->andWhereIn('parent', $parent);
            } else {
                $query->andWhere('parent=?', $parent);
            }
        }
        $query->orderBy('priority desc');
        $result = $query->execute();
        if ($result) {
            return $result;
        }
        return false;
    }

    public static function getAllAttrByCbx($status = false, $parent = false, $id = false)
    {
        $arrCbx = [
            '0' => '-- Chọn thuộc tính --'
        ];
        $result = AdManageAttrTable::getAllAttr($status, $parent, $id);
        if ($result) {
            foreach ($result as $item) {
                $arrCbx[$item->id] = $item->name;
                if ($id !== false && $item->id == $id) {
                    unset($arrCbx[$item->id]);
                }
            }
        }
        return $arrCbx;
    }
}