<?php

/**
 * AdMetaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdMetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdMetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdMeta');
    }

    public static function deleteArticleMeta($productId, $catId)
    {
        $query = AdMetaTable::getInstance()->createQuery()
            ->delete()
            ->where('product_id=?', $productId)
            ->andWhere('cat_id=?', $catId);
        return $query->execute();
    }
}