## YAML Template.
---
indexSuccess:
  metas:
    title: Danh sách phòng
newSuccess:
  metas:
    title: Thêm mới phòng
editSuccess:
  metas:
    title: Chỉnh sửa phòng
  javascripts:
    - /js/select2/select2.min.js
    - /js/select2/update.js
  stylesheets:
    - /js/select2/select2.min.css