<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/08/01 02:02:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vt_lapdm',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
