<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/08/01 02:02:45
sfConfig::add(array(
  'app_tmcTwitterBootstrapPlugin_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap.min.css',
  'app_tmcTwitterBootstrapPlugin_responsive_bootstrap_path' => '/tmcTwitterBootstrapPlugin/css/bootstrap-responsive.min.css',
  'app_tmcTwitterBootstrapPlugin_admin_styles_path' => '/tmcTwitterBootstrapPlugin/css/styles.css',
  'app_tmcTwitterBootstrapPlugin_jquery_path' => '/tmcTwitterBootstrapPlugin/js/jquery.min.js',
  'app_tmcTwitterBootstrapPlugin_bootstrap_js_path' => '/tmcTwitterBootstrapPlugin/js/bootstrap.min.js',
  'app_tmcTwitterBootstrapPlugin_admin_js_path' => '/tmcTwitterBootstrapPlugin/js/global.js',
  'app_tmcTwitterBootstrapPlugin_header' => array (
  'menu' => 
  array (
    'Phân hệ Tin tức' => 
    array (
      'credentials' => 
      array (
        0 => 
        array (
          0 => 'admin',
          1 => 'news_editor',
          2 => 'news_approved',
          3 => 'news_public',
          4 => 'ctv',
        ),
      ),
      'dropdown' => 
      array (
        'Quản lý tin đợi duyệt' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'news_editor',
              2 => 'news_approved',
              3 => 'news_public',
              4 => 'ctv',
            ),
          ),
          'route' => 'ad_article',
          'icon' => 'text.png',
        ),
        'Quản lý tin đợi đăng' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'news_editor',
              2 => 'news_approved',
              3 => 'news_public',
              4 => 'ctv',
            ),
          ),
          'route' => 'ad_article_adArticlesAproved',
          'icon' => 'text.png',
        ),
        'Quản lý tin đã đăng' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'news_editor',
              2 => 'news_approved',
              3 => 'news_public',
              4 => 'ctv',
            ),
          ),
          'route' => 'ad_article_adArticlesPublish',
          'icon' => 'text.png',
        ),
      ),
    ),
    'Phân hệ sản phẩm' => 
    array (
      'credentials' => 
      array (
        0 => 
        array (
          0 => 'admin',
          1 => 'product',
        ),
      ),
      'dropdown' => 
      array (
        'Danh sách chuyên mục sản phẩm' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'hq_product_cat',
            ),
          ),
          'route' => 'vtp_products_category',
          'icon' => 'text.png',
        ),
        'Danh sách sản phẩm' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'hq_product',
            ),
          ),
          'route' => 'vtp_products',
          'icon' => 'text.png',
        ),
        'Danh sách ảnh sản phẩm' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'hq_product_image',
            ),
          ),
          'route' => 'vtp_product_image',
          'icon' => 'text.png',
        ),
        'Danh sách nhà cung cấp' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'hq_brand',
            ),
          ),
          'route' => 'hq_brand',
          'icon' => 'text.png',
        ),
        'Danh sách Dịch vụ' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'hq_brand',
            ),
          ),
          'route' => 'ad_product',
          'icon' => 'text.png',
        ),
        'Danh sách Thuộc Tính' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'product',
              2 => 'ad_attr',
            ),
          ),
          'route' => 'ad_manage_attr',
          'icon' => 'text.png',
        ),
      ),
    ),
    'Phân hệ khác' => 
    array (
      'credentials' => 
      array (
        0 => 
        array (
          0 => 'admin',
          1 => 'subAdmin',
          2 => 'ctv',
        ),
      ),
      'dropdown' => 
      array (
        'Quản lý chuyên mục tin tức' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'vtp_category',
          'icon' => 'squares36.png',
        ),
        'Quản lý nội dung' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'subAdmin',
            ),
          ),
          'route' => 'ad_html',
          'icon' => 'text.png',
        ),
        'Vị trí quảng cáo' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'subAdmin',
            ),
          ),
          'route' => 'ad_advertise_location',
          'icon' => 'computer.png',
        ),
        'Quản lý Banner - quảng cáo' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
              1 => 'subAdmin',
            ),
          ),
          'route' => 'ad_advertise',
          'icon' => 'computer.png',
        ),
        'Quản lý liên kết' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'ad_link',
          'icon' => 'link71.png',
        ),
        'Quản lý đơn hàng' => 
        array (
          'credentials' => 
          array (
            0 => 
            array (
              0 => 'admin',
            ),
          ),
          'route' => 'booking',
          'icon' => 'text.png',
        ),
      ),
    ),
    'Quản trị hệ thống' => 
    array (
      'credentials' => 
      array (
        0 => 'admin',
      ),
      'dropdown' => 
      array (
        'Danh sách người dùng' => 
        array (
          'route' => 'sf_guard_user',
          'icon' => 'users6.png',
        ),
        'Danh sách quyền hạn' => 
        array (
          'route' => 'sf_guard_permission',
          'icon' => 'users6.png',
        ),
        'Quản lý cấu hình' => 
        array (
          'route' => 'ad_config',
          'icon' => 'users6.png',
        ),
      ),
    ),
    'Ngôn ngữ' => 
    array (
      'dropdown' => 
      array (
        'Tiếng Việt' => 
        array (
          'route' => 'pageVI',
          'icon' => 'users6.png',
        ),
        'Tiếng Anh' => 
        array (
          'route' => 'pageEN',
          'icon' => 'users6.png',
        ),
      ),
    ),
  ),
),
  'app_sf_captchagd_image_width' => 180,
  'app_sf_captchagd_image_height' => 27,
  'app_sf_captchagd_charset' => 'ABCDEFGHJKLMNPRSTUXYZabcdefghkmnprstuyz23456789',
  'app_sf_captchagd_code_length_min' => 2,
  'app_sf_captchagd_code_length_max' => 2,
  'app_sf_captchagd_perturbation' => 0.29999999999999999,
  'app_sf_captchagd_num_lines' => 1,
  'app_sf_captchagd_noise_level' => 2,
  'app_sf_captchagd_use_transparent_text' => true,
  'app_sf_captchagd_text_transparency_percentage' => 10,
  'app_sf_captchagd_image_bg_color' => 'ffffff',
  'app_sf_captchagd_text_color' => 252525,
  'app_sf_captchagd_line_color' => 616161,
  'app_sf_captchagd_chars' => '123456789abcdefghijklmnopqrstuvwxyz',
  'app_sf_captchagd_length' => 2,
  'app_sf_captchagd_font_size' => 14,
  'app_sf_captchagd_force_new_captcha' => true,
  'app_sf_captchagd_fonts' => array (
  0 => 'akbar/vavobi.ttf',
),
  'app_image_maxsize' => 52428800,
  'app_upload_max_size' => 104857600,
  'app_image_upload_max_size' => 52428800,
  'app_upload_video_max_size' => 50485760,
  'app_excel_max_row' => 1000,
  'app_category_images' => 'category_images',
  'app_article_images' => 'article',
  'app_service_images' => 'service',
  'app_advertise_images' => 'advertise',
  'app_product_images' => 'products',
  'app_import_max_size' => 1048576,
  'app_album_images' => 'album',
  'app_video_images' => 'video',
  'app_document' => 'document',
  'app_member_images' => 'member',
  'app_image_default' => 'http://glovimex.com/images/default-image.jpg',
  'app_upload_member' => '/root/apps/project/hqtimex/web/uploads',
  'app_upload_media_file' => '/root/apps/project/glovimex/web/uploads',
  'app_url_media_file' => '/uploads',
  'app_url_media_default_file' => 'http://glovimex.com/images/default-image.jpg',
  'app_ckeditor_basePath' => '/js/ckeditor',
  'app_ckfinder_active' => true,
  'app_ckfinder_basePath' => '/js/ckfinder',
  'app_addcslashes_charlist' => '%_-\\\'',
  'app_seo_title' => 'GLOVIMEX',
  'app_seo_description' => 'GLOVIMEX',
  'app_seo_keywords' => 'GLOVIMEX',
  'app_seo_ogImage' => '',
  'app_seo_url' => 'http://glovimex.com',
  'app_ManageAdChainImage_maxsize' => 999999,
  'app_ManageAdChainImage_prefix' => 'chain',
  'app_ManageAdChainImage_type' => 'image/jpeg|image/jpg|image/png|image/gif',
  'app_domain' => 'http://glovimex.com',
));
