<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/08/01 02:10:05
sfConfig::add(array(
  'mod_vtpmanageproductscategory_enabled' => true,
  'mod_vtpmanageproductscategory_view_class' => 'sfPHP',
));
