<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/08/01 02:10:05
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'product',
        2 => 'hq_product_cat',
      ),
    ),
  ),
);
