<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/08/01 02:02:50
sfConfig::add(array(
  'mod_tmctwitterbootstrap_enabled' => true,
  'mod_tmctwitterbootstrap_view_class' => 'sfPHP',
));
