## YAML Template.
---
indexSuccess:
  metas:
    title: Danh sách danh mục sản phẩm
newSuccess:
  metas:
    title: Thêm mới danh mục sản phẩm
editSuccess:
  metas:
    title: Chỉnh sửa danh mục sản phẩm
  javascripts:
    - /js/select2/select2.min.js
    - /js/select2/update.js
  stylesheets:
    - /js/select2/select2.min.css