generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           Booking
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          booking
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        full_name: {label: "Họ tên"}
        phone: {label: "SĐT"}
        email: {label: "Email"}
        category_id: {label: "Căn"}
        product_id: {label: "Sản phẩm"}
        from_time: {label: "Từ ngày"}
        to_time: {label: "Đến ngày"}
        number_person: {label: "Số người"}
        number_room: {label: "Số phòng"}
        is_check: {label: "Trạng thái"}
        total: {label: "Số lượng"}
        total_price: {label: "Tổng tiền"}
        book_type: {label: "Loại đặt hàng"}
        requirement: {label: "Yêu cầu"}
      list:
        display: [full_name, phone,email, book_type, product_id, is_check, requirement]
        title: Danh sánh ảnh phòng
        object_actions:
          _edit: {label: Chi tiết}
          _delete: ~
      filter:
        class: BookingFormFilterAdmin
        display: [full_name, phone, email, is_check,book_type]
      form:
        display: [full_name, phone,email, book_type, product_id, requirement, is_check]
        class: BookingAdminForm
      edit:
        title: Chỉnh sửa đơn hàng
      new:
        title: Thêm mới đơn hàng
